# Source: bucketrepo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucketrepo-bucketrepo
  labels:
    draft: draft-app
    chart: "bucketrepo-0.1.67"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'bucketrepo'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bucketrepo-bucketrepo
  template:
    metadata:
      labels:
        draft: draft-app
        app: bucketrepo-bucketrepo
      annotations:
        checksum/config: "e4eb9e4600079b6269234f92d4eb0772e0537e685f847544b7fc810254517ae0"
    spec:
      containers:
        - name: bucketrepo
          image: "ghcr.io/jenkins-x/bucketrepo:0.1.67"
          imagePullPolicy: IfNotPresent
          command: ["/home/nonroot/bucketrepo"]
          args:
            - "-config-path=/config"
            - "-log-level=info"
          env:
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      securityContext:
        fsGroup: 65534
      terminationGracePeriodSeconds: 10
      serviceAccountName: bucketrepo-bucketrepo
      volumes:
        - name: config
          secret:
            secretName: bucketrepo-config
