# Source: bucketrepo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bucketrepo
  labels:
    chart: "bucketrepo-0.1.67"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
    meta.helm.sh/release-name: 'bucketrepo'
  namespace: jx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: bucketrepo-bucketrepo
