# Source: jxboot-helmfile-resources/templates/local-secrets.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jx-local-secrets
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: local
  data:
    - name: secrets.yaml
      key: secrets.yaml
      property: secrets.yaml
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'jxboot-helmfile-resources'
    type: Opaque
