# Source: lighthouse/templates/hmacsecret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse-hmac-token
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-1.1.52"
    release: "lighthouse"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"lighthouse-hmac-token","properties":[{"name":"hmac","question":"Lighthouse webhook token","help":"The webhook token is used as a secret to verify webhooks come from a trusted source","generator":"hmac"}],"mandatory":true}'
spec:
  backendType: local
  data:
    - name: hmac
      key: hmac
      property: hmac
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'lighthouse'
        secret.jenkins-x.io/schema-object: '{"name":"lighthouse-hmac-token","properties":[{"name":"hmac","question":"Lighthouse webhook token","help":"The webhook token is used as a secret to verify webhooks come from a trusted source","generator":"hmac"}],"mandatory":true}'
      labels:
        app: lighthouse-lighthouse
        chart: "lighthouse-1.1.52"
        release: "lighthouse"
        heritage: "Helm"
    type: Opaque
